describe('template spec', () => {
  beforeEach(() => {
    // we will create a new alias before each test
    cy.visit('https://demowebshop.tricentis.com/register')
  })
  it('Success Register', () => {
    cy.get('#gender-female')
    cy.get('#FirstName').type('Nofia')
    cy.get('#LastName').type('Hidayati')
    cy.get('#Email').type('nofia@gmail.com')
    cy.get('#Password').type('nofia123')
    cy.get('#ConfirmPassword').type('nofia123')
    cy.get('#register-button').click()
    // cy.get('.page-body > .buttons > .button-1').click()
  })
  it('Failed Register - Wrong Confirm Password', () => {
    cy.get('#gender-female')
    cy.get('#FirstName').type('Nofia')
    cy.get('#LastName').type('Hidayati')
    cy.get('#Email').type('nofia@gmail.com')
    cy.get('#Password').type('nofia123')
    cy.get('#ConfirmPassword').type('@nofia123')
    cy.get('#register-button').click()
  //   cy.get('.page-body > .buttons > .button-1').click()
  })
  it('Failed Register - Invalid Email', () => {
    cy.get('#gender-female')
    cy.get('#FirstName').type('Nofia')
    cy.get('#LastName').type('Hidayati')
    cy.get('#Email').type('nofia1500')
    cy.get('#Password').type('nofia123')
    cy.get('#ConfirmPassword').type('nofia123')
    cy.get('#register-button').click()
  //   cy.get('.page-body > .buttons > .button-1').click()
  })
  it('Success Register - Gender Are Not Choice', () => {
    cy.get('#FirstName').type('Nofia')
    cy.get('#LastName').type('Hidayati')
    cy.get('#Email').type('nofia15002000@gmail.com')
    cy.get('#Password').type('nofia123')
    cy.get('#ConfirmPassword').type('nofia123')
    cy.get('#register-button').click()
  //   cy.get('.page-body > .buttons > .button-1').click()
  })
})